apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ex
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iam-dasari/argocd.git   # Replace it with your forked repo
    targetRevision: main
    path: .
  destination:
    server:  https://kubernetes.default.svc   # Replace with your Cluster Url, To get run: `argocd cluster list`
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    